iteration_num: 
  type: generation_param
  value: 1
model: 
  type: generation_param
  value: gpt-4o-mini

creativity_id: 
  type: necessary_column
  value: [3]
length_id: 
  type: necessary_column
  value: [3,4,5]
system_prompt_id: 
  type: necessary_column
  value: [1,2,3,4,5]
generation_prompt_id: 
  type: necessary_column
  value: [1]
form_id: 
  type: necessary_column
  value: [4]
mapping_emotion_form_id: 
  type: necessary_column
  value: 10~12
speaker_id: 
  type: necessary_column
  value: [1]
style_id: 
  type: necessary_column
  value: [1]
key_expression_id: 
  type: optional_column
  value: []
theme_id: 
  type: optional_column
  value: 1~7
example: 
  type: target_column
  value: []
etc: 
  type: optional_column
  value: []